/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/state/group": {
    delete: {
      parameters: {
        query: {
          groupId: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state/group/name": {
    put: {
      parameters: {
        query: {
          groupId: string;
          newName: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state/group/theme": {
    put: {
      parameters: {
        query: {
          groupId: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json":
            | components["schemas"]["LedTheme"]
            | components["schemas"]["LedThemeDaylight"]
            | components["schemas"]["LedThemeSingleColor"];
          "text/json":
            | components["schemas"]["LedTheme"]
            | components["schemas"]["LedThemeDaylight"]
            | components["schemas"]["LedThemeSingleColor"];
          "application/*+json":
            | components["schemas"]["LedTheme"]
            | components["schemas"]["LedThemeDaylight"]
            | components["schemas"]["LedThemeSingleColor"];
        };
      };
    };
  };
  "/state/group/theme-preview": {
    get: {
      parameters: {
        query: {
          groupId: string;
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            "image/png": string;
          };
        };
      };
    };
  };
  "/state/segment/move": {
    put: {
      parameters: {
        query: {
          segmentId: string;
          targetGroupId?: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state/segment/name": {
    put: {
      parameters: {
        query: {
          segmentId: string;
          newName: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["DataStoreRoot"];
          };
        };
      };
    };
  };
  "/state/activated": {
    put: {
      parameters: {
        query: {
          newActivated: boolean;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/theme-types": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["LedThemeTypes"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Color: {
      /** Format: int32 */
      r?: number;
      /** Format: int32 */
      g?: number;
      /** Format: int32 */
      b?: number;
    };
    DataStoreRoot: {
      activated?: boolean;
      groups?: components["schemas"]["LedSegmentGroup"][] | null;
    };
    LedSegment: {
      wledServerAddress?: string | null;
      /** Format: int32 */
      segmentIndex?: number;
      name?: string | null;
      readonlyId?: string | null;
    };
    LedSegmentGroup: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
      ledSegments?: components["schemas"]["LedSegment"][] | null;
      theme?:
        | (
            | components["schemas"]["LedTheme"]
            | components["schemas"]["LedThemeDaylight"]
            | components["schemas"]["LedThemeSingleColor"]
          )
        | null;
      displayColor?: components["schemas"]["Color"];
      isEdited?: boolean;
    };
    LedTheme: {
      typeName?: string | null;
      /** Format: uuid */
      id?: string;
      modifiers?: components["schemas"]["LedThemeModifier"][] | null;
    };
    LedThemeDaylight: components["schemas"]["LedTheme"] & {
      skyColor?: components["schemas"]["Color"];
      sunColor?: components["schemas"]["Color"];
      /** Format: double */
      invertedSunSize?: number;
    };
    LedThemeModifier: { [key: string]: unknown };
    LedThemeSingleColor: components["schemas"]["LedTheme"] & {
      color?: components["schemas"]["Color"];
      /** Format: int32 */
      brightness?: number;
    };
    LedThemeTypes: {
      themes?: components["schemas"]["TypeInfo"][] | null;
      modifiers?: components["schemas"]["TypeInfo"][] | null;
    };
    TypeInfo: {
      name?: string | null;
      typeDiscriminator?: string | null;
      properties?: components["schemas"]["TypePropertyInfo"][] | null;
    };
    TypePropertyInfo: {
      name?: string | null;
      type?: string | null;
      defaultValue?: unknown | null;
    };
  };
}

export interface operations {}

export interface external {}
