/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/state": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["DataStoreRoot"];
          };
        };
      };
    };
  };
  "/state/group/rename": {
    put: {
      parameters: {
        query: {
          groupId: string;
          newName: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state/group/theme": {
    put: {
      parameters: {
        query: {
          groupId: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
      requestBody: {
        content: {
          "application/json":
            | components["schemas"]["LedThemeDaylight"]
            | components["schemas"]["LedThemeSingleColor"];
        };
      };
    };
  };
  "/state/segment/move": {
    put: {
      parameters: {
        query: {
          segmentId: string;
          targetGroupId?: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state/segment/rename": {
    put: {
      parameters: {
        query: {
          segmentId: string;
          newName: string;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/state/activated": {
    put: {
      parameters: {
        query: {
          newActivated: boolean;
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/theme-types": {
    get: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["LedThemeTypes"];
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    Color: {
      /** Format: int32 */
      r?: number;
      /** Format: int32 */
      g?: number;
      /** Format: int32 */
      b?: number;
    };
    DataStoreRoot: {
      activated?: boolean;
      groups?: components["schemas"]["LedSegmentGroup"][] | null;
    };
    LedSegment: {
      wledServerAddress?: string | null;
      /** Format: int32 */
      segmentIndex?: number;
      name?: string | null;
      readonlyId?: string | null;
    };
    LedSegmentGroup: {
      /** Format: uuid */
      id?: string;
      name?: string | null;
      ledSegments?: components["schemas"]["LedSegment"][] | null;
      theme?:
        | (
            | components["schemas"]["LedThemeDaylight"]
            | components["schemas"]["LedThemeSingleColor"]
          )
        | null;
      displayColor?: components["schemas"]["Color"];
      isEdited?: boolean;
    };
    LedTheme: {
      type?: string | null;
      /** Format: uuid */
      id?: string;
      modifiers?: components["schemas"]["LedThemeModifier"][] | null;
    };
    LedThemeDaylight: components["schemas"]["LedTheme"] & {
      skyColor?: components["schemas"]["Color"];
      sunColor?: components["schemas"]["Color"];
      /** Format: double */
      invertedSunSize?: number;
    };
    LedThemeImpl: {
      name?: string | null;
      properties?: components["schemas"]["LedThemeImplProperty"][] | null;
    };
    LedThemeImplProperty: {
      name?: string | null;
      type?: string | null;
    };
    LedThemeModifier: { [key: string]: unknown };
    LedThemeModifierImpl: {
      name?: string | null;
      properties?:
        | components["schemas"]["LedThemeModifierImplProperty"][]
        | null;
    };
    LedThemeModifierImplProperty: {
      name?: string | null;
      type?: string | null;
    };
    LedThemeSingleColor: components["schemas"]["LedTheme"] & {
      color?: components["schemas"]["Color"];
      /** Format: int32 */
      brightness?: number;
    };
    LedThemeTypes: {
      themes?: components["schemas"]["LedThemeImpl"][] | null;
      modifiers?: components["schemas"]["LedThemeModifierImpl"][] | null;
    };
  };
}

export interface operations {}

export interface external {}
